// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Username string `json:"username"`
}

type UserCreateResponse struct {
	UserID   *string `json:"userId"`
	Username *string `json:"username"`
	Email    *string `json:"email"`
}

type UserDeleteResponse struct {
	UserID *string `json:"userId"`
}

type UserReferralCreatedResponse struct {
	UserID            *string `json:"userId"`
	ReferredUserEmail *string `json:"referredUserEmail"`
}
